### ISSUE TITLE
Bad syntax with flex

### ISSUE THREAD

**Issue by nicomollet** [matthiasmullie/minify#235]
Hello

On my website https://www.restaurant-caphorn.fr/ I have a rule in my CSS for the logo alignment:
```css
#site-header.medium-header .top-col.logo-col{
    -webkit-flex: auto 0 0;
    flex: auto 0 0;
}
```

which once minified/compressed and is becoming:
```css
#site-header.medium-header .top-col.logo-col {
    -webkit-flex: auto 0 0%;
    flex: auto 0 0%;
}
```

`flex: auto 0 0%;` is not valid CSS, so it breaks the effect I wanted to do. (I overrided it the rule temporarily on my website to fix it).
Can this be fixed?

(Using latest version, inside WP Rocket plugin for WordPress.)
Kind regards

Thank you.
Nico
