### ISSUE TITLE
Trailing semicolon when moveImportsToTop

### ISSUE THREAD

**Issue by jeremie-walkwizus** [matthiasmullie/minify#240]
Hi,

I think there is a little problem in the moveImportsToTop method.

This for example :

```css
p{color:red}
@import url("http://minify.dev/?a=1&amp;b=some/*lala*/thing");
body{font-family:sans-serif}
```

Results to this :

```css
@import url(http://minify.dev/?a=1&amp;b=some/*lala*/thing);p{color:red};body{font-family:sans-serif}
```

There is a trailing semicolon next to the "body" selector which makes the css invalid.

Can you fix the regex, please ?

Thank you
