### ISSUE TITLE
CSS minifier deletes .0 in url string

### ISSUE THREAD

**Issue by t2oh4e** [matthiasmullie/minify#28]
Hi there!

I'm currently trying out your minifier which works really nice but I found a problem.
I have a CSS-File with this part:

```css
@font-face {
  font-family: 'FontAwesome';
  src: url('//netdna.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.eot?v=4.2.0');
  src: url('//netdna.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.eot?#iefix&v=4.2.0') format('embedded-opentype'), url('//netdna.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.woff?v=4.2.0') format('woff'), url('//netdna.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.ttf?v=4.2.0') format('truetype'), url('//netdna.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.svg?v=4.2.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
In the src url there is an part 4.2.0 which is minified to 4.2 which leads to the following url:
//netdna.bootstrapcdn.com/font-awesome/4.2/fonts/fontawesome-webfont.eot?v=4.2
instead of the correct one.
shortened part of the above CSS after minification:
```css
src:url(//netdna.bootstrapcdn.com/font-awesome/4.2/fonts/fontawesome-webfont.eot?v=4.2);
```
I tried this with double- and single-quotes as well as no quotes at all.
Any suggestions? For now I removed this line and it seems to work correctly: https://github.com/matthiasmullie/minify/blob/master/src/CSS.php#L370
