### ISSUE TITLE
Problems with semicolon in function "moveImportsToTop"

### ISSUE THREAD

**Issue by SventB** [matthiasmullie/minify#289]
There's a problem with function "moveImportsToTop":
If it converts following CSS:

```css
@charset "UTF-8";@import url(//fast.fonts.net/t/1.css?apiType=...);.aa{display:block}
```
The resulting (invalid) CSS is this:

```css
@import url(//fast.fonts.net/t/1.css?apiType=...);@charset "UTF-8".aa{display:block}
```

This is invalid: `"UTF-8".aa`

It seems the problem is the `(;?)` in the regex:

```php
preg_match_all('/(;?)(@import (?<url>url\()?(?P<quotes>["\']?).+?(?P=quotes)(?(url)\)));?/', $content, $matches)
```
This results in $matches[0]:
```
array(1) { [0]=> string(98) ";@import url(//fast.fonts.net/t/1.css?apiType=...);" }
```
The prefixed semicolon seems wrong.
