### ISSUE TITLE
css variable 0px should not be minified to 0

### ISSUE THREAD

**Issue by tiansh** [matthiasmullie/minify#298]
Related: #137, #217

Consider

```css
:root {
--some-var: 0px;
}
p {
margin-left: calc(20px + var(--some-var));
}
```

`0px` should not be modified to 0.
