### ISSUE TITLE
Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /plugins/matthiasmullie/minify/CSS.php on line 518

### ISSUE THREAD

**Issue by AnnoyingTechnology** [matthiasmullie/minify#335]
This is encountered with PHP 7.4.6, passing some raw CSS (very little) to the constructor. 

piece of CSS used as a test

```css
h1 {
	font-size: 72px;
	padding-bottom: 40px;
}
.names {
	color: red;
	padding: 25px;
	font-size: 26px;
}
```
