### ISSUE TITLE
Don't transform flex-basis: 0 into flex-basis: 0%

### ISSUE THREAD

**Issue by Golmote** [matthiasmullie/minify#368]
Hello,

When given this code:
```css
.foo {
    flex-basis: 0;
}
```

or this code:
```css
.foo {
    flex-basis: 0px;
}
```

the minifier transform the value into `0%`:
```css
.foo{flex-basis:0%}
```

This is an issue because using percentages for flex-basis [does not produce the same result](https://stackoverflow.com/questions/63475073/css-flex-basis-0-has-different-behaviour-to-flex-basis-0px).

This issue also happens when using the `flex` shorthand:
```css
.foo {
    flex: 1 0 0;
}
.bar {
    flex: 1 0 0px;
}
```
gives
```css
.foo{flex:1 0 0%}.bar{flex:1 0 0%}
```
