### ISSUE TITLE
CSS variable with leading whitespaces 0px should not be minified to 0

### ISSUE THREAD

**Issue by Cacodaimon** [matthiasmullie/minify#378]
A CSS variable with leading white spaces and 0px gets minified to 0, happens e.g. with https://tailwindcss.com/docs/ring-offset-width and leads to an CSS `calc` issue.

Example:

https://github.com/matthiasmullie/minify/compare/0cf6c085b1dde107e375a5938e2e5033640de0e0...Cacodaimon:master

```css
:root {
  --some-var: 0px;
}
p {
margin-left: calc(20px + var(--some-var));
}

```

Gets minifed to:

```css
:root{--some-var:0}.some-class{margin-left:calc(20px + var(--some-var))}
```

Related: https://github.com/matthiasmullie/minify/issues/298
