### ISSUE TITLE
CSS encode base64

### ISSUE THREAD

**Issue by antiqar** [matthiasmullie/minify#49]
For some reason minifier do not encode image to base64 string only on first element with background-image property.

CSS:
```css
.social-btn a[href*="facebook"] { background-image: url(facebook.png) } /* encode skipped */
.social-btn a[href*="vimeo"] { background-image: url(vimeo.png) }
.social-btn a[href*="instagram"] { background-image: url(instagram.png) }
```

PHP:
```php
$cssMinifier = new Minify\CSS( 'styles.css' );
$cssMinifier->setMaxImportSize(10); /*  All images < 10 kb */
echo $cssMinifier->minify();
```
