### ISSUE TITLE
Remove empty CSS tags?

### ISSUE THREAD

**Issue by gabel** [matthiasmullie/minify#67]
Of course they shouldn't exist, but if so could the CSS minifier remove empty CSS tags?

Example: 
```css
body { }
p { color: #fff; }
```

Result:
```css
body{}p{color:#fff}
```

Expected Result:
```css
p{color:#fff}
```

**Comment by matthiasmullie** [comment]
Hi @gabel - Thanks for the great idea!
I've just added that. It'll be included in the next release!

**Comment by kaittodesk** [comment]
Just a heads up. When I tested the fix for issue #70 against the HEAD of master branch I found that it broke my CSS minification as it contained multiple empty CSS tags.

A simple CSS:
```css
body {}
p { color: #fff; }
h1 { }
strong { color: red; }
```
will result in
```css
strong{color:red}
```
but it should be
```css
p{color:#fff}
strong{color:red}
```

Looks like the regular expression removes everything before the last occurrence of any empty CSS tag.
