### ISSUE TITLE
Issue with empty media-queries

### ISSUE THREAD

**Issue by bugalot** [matthiasmullie/minify#92]
Hello @matthiasmullie !

First of all, thanks for this wonderful project which helps so many people in developing web applications !

I think I discovered an issue occurring with media queries. Basically, If a @media() rule is left empty of any selector - _e.g. @media (min-width:1025px){}_, the preceding @media() rule will be malformed ("}" missing char at the end). 

Let me illustrate that by an example. I just built a little project to illustrate this example. It will make it easier to understand and reproduce the issue.The project is composed by 3 files:

* composer.json which refers to version 1.3.29 of your minifier library.
* minify.css which represents the file to be minified, containing media queries.
* minify.php which echoes the result of the minify.css minification.

Please find below the content of these files:

**composer.json**
```json
{
	"name": "minifier/test",
	"description": "Minifier Test",
	"type": "library",
	"require" : {
        "matthiasmullie/minify": "1.3.29"
	}
}
```

**minify.css**
```css
@media (min-width:320px) {
    /* smartphones, iPhone, portrait 480x320 phones */
    p {
        background-color: red;
    }
}
@media (min-width:1025px) {
    /* big landscape tablets, laptops, and desktops */
    /* LEFT EMPTY OF ANY SELECTORS */
}
@media (min-width:1281px) {
    /* hi-res laptops and desktops */
    p {
        background-color: blue;
    }
}
```

**minify.php**
```php
<?php
require('vendor/autoload.php');

use MatthiasMullie\Minify;

$minifier = new Minify\CSS('minify.css');
echo $minifier->minify() . "\n";
```

If it is expected that empty @media rules are removed at minification time, we would expect the output of minify.php to be:

```css
@media (min-width:320px){p{background-color:red}}@media (min-width:1281px){p{background-color:white}}
```

However, the output of minify.php is:

```css
@media (min-width:320px){p{background-color:red}@media (min-width:1281px){p{background-color:white}}
```

**There is a missing "}" character after the "red" color so that web browsers will fail at understanding the media query (at least in the last version of Firefox).**

I hope that the description of the issue will be clear to you, and that it will help you in making your wonderful library always better!

All the best
